### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by RahulGupta899** [Bauddhik-Geeks/BG-Color-Switch#1]
- Not responsive for Mobile phones
- I would like to work on this

**Comment by kamleshjoshi8102** [comment]
Go ahead @RahulGupta899

**Comment by Nitesh-thapliyal** [comment]
> * Not responsive for Mobile phones
> * I would like to work on this

any update on the issue?

**Comment by RahulGupta899** [comment]
Busy with clg work, I will complete it by sunday

**Comment by RahulGupta899** [comment]
This issue is already resolved by someone
