### ISSUE TITLE
[Feature] Click to copy background color

### ISSUE THREAD

**Issue by g7i** [Bauddhik-Geeks/BG-Color-Switch#10]
I would like to implement this feature.
![Screenshot from 2021-10-02 13-27-05](https://user-images.githubusercontent.com/46393634/135709428-55d94d33-03ae-44fa-a626-94acf34567c5.png)
![Screenshot from 2021-10-02 13-27-38](https://user-images.githubusercontent.com/46393634/135709430-e0055776-68c2-4456-ae7c-847cdd764c71.png)

**Comment by yadavashishdhirendra** [comment]
Hey, @g7i I would Like to contribute this feature can you please assign it to me!

**Comment by Nitesh-thapliyal** [comment]
> Hey, @g7i I would Like to contribute this feature can you please assign it to me!

This issue PR is already been made, you can check out other repos 😊
