### ISSUE TITLE
[Feature]Add CSS to the button

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/BG-Color-Switch#2]

**Comment by SamikshaSankar** [comment]
Please assign this issue

**Comment by singlapriyanka315** [comment]
Assign me this issue.

**Comment by NikitaK27** [comment]
Please assign me this issue

**Comment by rajmunkhan** [comment]
@Nitesh-thapliyal I would like to contribute here, please assign it to me.

**Comment by kamleshjoshi8102** [comment]
go Ahead @singlapriyanka315

**Comment by kamleshjoshi8102** [comment]
@SamikshaSankar @rajmunkhan @niku123K You can explore other repositories too : )

**Comment by Nitesh-thapliyal** [comment]
Closing this issue because work as already been done on this issue
