### ISSUE TITLE
[Feature] Add gradient backgrounds

### ISSUE THREAD

**Issue by g7i** [Bauddhik-Geeks/BG-Color-Switch#8]
@Nitesh-thapliyal 
If possible plz label it for **hacktoberfest** and would like to work on this. Thanks

**Comment by g7i** [comment]
I'll show the gradients randomly in between the colors.

**Comment by Nitesh-thapliyal** [comment]
> I'll show the gradients randomly in between the colors.

Can you share a snapshot for the clear view how exactly it will look like

**Comment by g7i** [comment]
![Screenshot from 2021-10-02 12-39-56](https://user-images.githubusercontent.com/46393634/135707228-a6615193-d773-4f88-8d23-ec4776a6e22c.png)


> > I'll show the gradients randomly in between the colors.
> 
> Can you share a snapshot for the clear view how exactly it will look like

**Comment by himanshucyborg** [comment]
Assign me on this issue.
